version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    volumes:
      - .db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: p2y_wordpress
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  my-wp:
    build: .
    ports:
      - "80:80"
    links:
      - my-wpdb:mysql
    volumes:
      - './:/var/www/html'
    environment:
      WORDPRESS_DB_NAME: p2y_wordpress
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
